{% set name = "pytest-codspeed" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_codspeed-{{ version }}.tar.gz
  sha256: f29641d27b4ded133b1058a4c859e510a2612ad4217ef9a839ba61750abd2f8a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
    - cffi >=1.17.1
    - valgrind >=3.21
  run:
    - python >={{ python_min }}
    - cffi >=1.17.1
    - setuptools
    - pytest >=3.8
    - rich >=13.8.1
    - importlib-metadata >=8.5.0

test:
  imports:
    - pytest_codspeed
    - pytest_codspeed.instruments.valgrind._wrapper.dist_callgrind_wrapper
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://codspeed.io/
  summary: Pytest plugin to create CodSpeed benchmarks
  dev_url: https://github.com/CodSpeedHQ/pytest-codspeed
  doc_url: https://docs.codspeed.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - kenodegard
