{% set name = "pytest-codspeed" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_codspeed-{{ version }}.tar.gz
  sha256: f9d1b1a3b2c69cdc0490a1e8b1ced44bffbd0e8e21d81a7160cfdd923f6e8155

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=61
    - pip
    - cffi >=1.17.1
    - valgrind >=3.21
  run:
    - python
    - cffi >=1.17.1
    - setuptools
    - pytest >=3.8
    - rich >=13.8.1
    - importlib-metadata >=8.5.0

test:
  imports:
    - pytest_codspeed
    - pytest_codspeed.instruments.valgrind._wrapper.dist_callgrind_wrapper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://codspeed.io/
  summary: Pytest plugin to create CodSpeed benchmarks
  dev_url: https://github.com/CodSpeedHQ/pytest-codspeed
  doc_url: https://docs.codspeed.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - kenodegard
