schema_version: 1

context:
  name: pytest-codspeed
  version: "4.1.1"
  build: 0
  # build noarch on osx
  noarch: ${{ osx }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pytest_codspeed-${{ version }}.tar.gz
  sha256: 9acc3394cc8aafd4543193254831d87de6be79accfdbd43475919fdaa2fc8d81

build:
  number: 1
  skip: (not linux and not noarch) or (noarch and not python_min)
  script:
    content:
      - if: noarch
        then:
          - export PYTEST_CODSPEED_SKIP_EXTENSION_BUILD=1
        else:
          - export PYTEST_CODSPEED_FORCE_EXTENSION_BUILD=1
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    version_independent: ${{ noarch }}
  variant:
    # prefer non-noarch, if available
    down_prioritize_variant: ${{ 1 if noarch else 0 }}

requirements:
  build:
    - if: not noarch
      then:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
  host:
    - if: noarch
      then:
        - python ${{ python_min }}.*
      else:
        - python
    - setuptools >=61
    - pip
    - cffi >=1.17.1
    - if: not noarch
      then:
        - valgrind >=3.21
  run:
    - if: noarch
      then:
        - python >=${{ python_min }}
      else:
        - python
    - cffi >=1.17.1
    - setuptools
    - pytest >=3.8
    - rich >=13.8.1
    - importlib-metadata >=8.5.0

tests:
  - python:
      pip_check: true
      imports:
        - pytest_codspeed
        - if: not noarch
          then:
            - pytest_codspeed.instruments.hooks.dist_instrument_hooks

about:
  summary: Pytest plugin to create CodSpeed benchmarks
  license: MIT
  license_file: LICENSE
  homepage: https://codspeed.io/
  repository: https://github.com/CodSpeedHQ/pytest-codspeed
  documentation: https://docs.codspeed.io/

extra:
  recipe-maintainers:
    - xhochy
    - kenodegard
