schema_version: 1

context:
  name: pytest-codspeed
  version: "4.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pytest_codspeed-${{ version }}.tar.gz
  sha256: 0e9af08ca93ad897b376771db92693a81aa8990eecc2a778740412e00a6f6eaf

build:
  number: 1
  skip: not linux
  script:
    - export PYTEST_CODSPEED_FORCE_EXTENSION_BUILD=1
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - setuptools >=61
    - pip
    - cffi >=1.17.1
    - valgrind >=3.21
  run:
    - python
    - cffi >=1.17.1
    - setuptools
    - pytest >=3.8
    - rich >=13.8.1
    - importlib-metadata >=8.5.0

tests:
  - python:
      imports:
        - pytest_codspeed
        - pytest_codspeed.instruments.hooks.dist_instrument_hooks
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Pytest plugin to create CodSpeed benchmarks
  license: MIT
  license_file: LICENSE
  homepage: https://codspeed.io/
  repository: https://github.com/CodSpeedHQ/pytest-codspeed
  documentation: https://docs.codspeed.io/

extra:
  recipe-maintainers:
    - xhochy
    - kenodegard
