schema_version: 1

context:
  name: pytest-codspeed
  version: 3.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pytest_codspeed-${{ version }}.tar.gz
  sha256: f9d1b1a3b2c69cdc0490a1e8b1ced44bffbd0e8e21d81a7160cfdd923f6e8155

build:
  number: 0
  skip: not linux
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - setuptools >=61
    - pip
    - cffi >=1.17.1
    - valgrind >=3.21
  run:
    - python
    - cffi >=1.17.1
    - setuptools
    - pytest >=3.8
    - rich >=13.8.1
    - importlib-metadata >=8.5.0

tests:
  - python:
      imports:
        - pytest_codspeed
        - pytest_codspeed.instruments.valgrind._wrapper.dist_callgrind_wrapper
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Pytest plugin to create CodSpeed benchmarks
  license: MIT
  license_file: LICENSE
  homepage: https://codspeed.io/
  repository: https://github.com/CodSpeedHQ/pytest-codspeed
  documentation: https://docs.codspeed.io/

extra:
  recipe-maintainers:
    - xhochy
    - kenodegard
